//
//  Patch+Helpers.swift
//  brWave
//
//  Convenience helpers for Patch, PatchSet, and PatchSlot.
//  NSManagedObject subclasses are auto-generated by Xcode from the model.
//
//  Position math: position = bank * 100 + program (0–199, 2 banks × 100 programs).
//

import CoreData

// MARK: - Patch

extension Patch {

    /// Populate the patch from a parsed Wave SysEx message.
    func importParsed(_ parsed: WaveParsedPatch) {
        // Behringer Wave firmware quirk: names in factory SysEx dumps are
        // filled with 0x31 ('1') — a placeholder, not the actual preset name.
        // Fall back to bank/program position so patches are distinguishable.
        let isPlaceholder = parsed.name.allSatisfy { $0 == "1" } || parsed.name.trimmingCharacters(in: .whitespaces).isEmpty
        let patchName: String
        if isPlaceholder {
            if let b = parsed.bank, let p = parsed.program {
                patchName = "B\(b) P\(String(format: "%02d", p))"
            } else {
                patchName = "Untitled"
            }
        } else {
            patchName = parsed.name
        }
        name            = patchName
        bank            = Int16(parsed.bank ?? -1)
        program         = Int16(parsed.program ?? -1)
        rawSysexPayload = Data(parsed.rawBytes)
        patchValues     = valuesFromParsed(parsed)
        dateCreated     = dateCreated ?? Date()
        dateModified    = Date()
        if uuid == nil { uuid = UUID() }
        // Wave has no native category field — classify from name keywords.
        category = PatchCategory.classify(patchName: patchName).rawValue
    }

    private func valuesFromParsed(_ parsed: WaveParsedPatch) -> WavePatchValues {
        var pv = WavePatchValues()
        // Shared params
        pv.setValue(parsed.wavetb, for: .wavetb, group: .a)
        pv.setValue(parsed.split,  for: .split,  group: .a)
        pv.setValue(parsed.keyb,   for: .keyb,   group: .a)
        // Per-group
        for (id, val) in parsed.groupA { pv.setValue(val, for: id, group: .a) }
        for (id, val) in parsed.groupB { pv.setValue(val, for: id, group: .b) }
        return pv
    }

    /// Encode/decode WavePatchValues to/from the `values` Binary attribute.
    var patchValues: WavePatchValues {
        get {
            guard let data = values,
                  let dict = try? JSONDecoder().decode([String: Int].self, from: data) else {
                return WavePatchValues()
            }
            var pv = WavePatchValues()
            for (key, val) in dict {
                // Keys are of form "DELAY_A", "DELAY_B", or "WAVETB" (shared)
                pv.setRaw(key: key, value: val)
            }
            return pv
        }
        set {
            values = try? JSONEncoder().encode(newValue.params)
        }
    }

    /// Read a single parameter value (0 if not yet set).
    func value(for id: WaveParamID, group: WaveGroup = .a) -> Int {
        patchValues.value(for: id, group: group)
    }

    /// Write a single parameter value, register undo, and notify UndoService.
    func setValue(_ value: Int, for id: WaveParamID, group: WaveGroup = .a) {
        let old = self.value(for: id, group: group)
        guard old != value else { return }

        managedObjectContext?.undoManager?.registerUndo(withTarget: self) { patch in
            patch.setValue(old, for: id, group: group)
        }

        var pv = patchValues
        pv.setValue(value, for: id, group: group)
        patchValues  = pv
        dateModified = Date()

        NotificationCenter.default.post(
            name: .waveParameterChanged, object: self,
            userInfo: ["id": id, "old": old, "new": value, "group": group]
        )
    }

    /// Raw 121-byte preset payload for lossless SysEx round-trip.
    var rawBytes: [UInt8] {
        guard let data = rawSysexPayload else { return [] }
        return [UInt8](data)
    }

    /// Build a preset SysEx message ready to send to the Wave at a specific slot.
    func toSysEx(bank: Int, program: Int) -> [UInt8] {
        WaveSysExParser.dumpToPreset(bank: bank, program: program, payload: rawBytes)
    }

    /// Build an edit buffer SysEx (immediate playback, no slot save).
    func toEditBufferSysEx() -> [UInt8] {
        WaveSysExParser.dumpToEditBuffer(payload: rawBytes)
    }
}

// MARK: - WavePatchValues raw key access

extension WavePatchValues {
    mutating func setRaw(key: String, value: Int) {
        params[key] = value
    }
}

// MARK: - PatchSet

extension PatchSet {

    /// Slots sorted by position.
    var slotsArray: [PatchSlot] {
        (slots as? Set<PatchSlot> ?? []).sorted { $0.position < $1.position }
    }

    /// O(n) position → Patch lookup for the bank grid.
    var patchByPosition: [Int: Patch] {
        slotsArray.reduce(into: [:]) { dict, slot in
            if let patch = slot.patch {
                dict[Int(slot.position)] = patch
            }
        }
    }

    var occupiedCount: Int {
        (slots as? Set<PatchSlot> ?? []).filter { $0.patch != nil }.count
    }

    /// Create a new PatchSet, deduplicating the name if needed.
    @discardableResult
    static func create(named rawName: String, in ctx: NSManagedObjectContext) -> PatchSet {
        var name = rawName
        var counter = 2
        let req: NSFetchRequest<PatchSet> = PatchSet.fetchRequest()
        while true {
            req.predicate = NSPredicate(format: "name == %@", name)
            req.fetchLimit = 1
            if (try? ctx.count(for: req)) == 0 { break }
            name = "\(rawName) (\(counter))"
            counter += 1
        }
        let ps = PatchSet(context: ctx)
        ps.uuid      = UUID()
        ps.name      = name
        ps.createdAt = Date()
        return ps
    }

    static func findOrCreate(named name: String, in ctx: NSManagedObjectContext) -> PatchSet {
        let req: NSFetchRequest<PatchSet> = PatchSet.fetchRequest()
        req.predicate = NSPredicate(format: "name == %@", name)
        req.fetchLimit = 1
        if let existing = try? ctx.fetch(req).first { return existing }
        return create(named: name, in: ctx)
    }
}

// MARK: - PatchSlot

extension PatchSlot {

    @discardableResult
    static func make(position: Int, patch: Patch?, in set: PatchSet,
                     ctx: NSManagedObjectContext) -> PatchSlot {
        let slot      = PatchSlot(context: ctx)
        slot.position = Int16(position)
        slot.patch    = patch
        slot.patchSet = set
        return slot
    }

    /// Wave: 2 banks × 100 programs. Position = bank * 100 + program (0–199).
    var bankIndex: Int    { Int(position) / 100 }
    var programIndex: Int { Int(position) % 100 }
}
